<?php
require_once 'PHPUnit/Framework.php';

require_once "File/CSV/GetSql.php";
require_once "File/CSV/tests/fixtures/csv.php";

/**
 * Test class for File_CSV_GetSql.
 * Generated by PHPUnit on 2008-10-08 at 20:48:00.
 */
class File_CSV_GetSqlTest extends PHPUnit_Framework_TestCase
{
    protected $csv;

    protected function setUp()
    {
        $this->csv = new File_CSV_GetSql;
    }

    protected function tearDown()
    {
        $this->csv = null;
    }

    public function testCreate_queries()
    {
        $this->assertTrue($this->csv->uses(path('symmetric.csv')));
        $expected = fix('symmetric_queries');
        $this->assertEquals($expected, $this->csv->createQueries('test_table'));
    }

    public function test_values_in_queries_must_not_have_trailing_spaces()
    {
        $fname = path('symmetric_with_trailing_spaces.csv');
        $this->assertTrue($this->csv->uses($fname));
        $expected = fix('symmetric_queries');
        $this->assertEquals($expected, $this->csv->createQueries('test_table'));
    }

    public function test_create_queries_with_alternate_columns()
    {
        $fname = path('symmetric.csv');
        $this->assertTrue($this->csv->uses($fname));
        $columns = array('header_a', 'header_c');
        $res = $this->csv->createQueries('test_table', $columns);
        $this->assertEquals(fix('alternated_header_queries'), $res);
    }

    public function testConvertable()
    {
    }


    public function test_convert()
    {
    }

}

?>
